# Generated by Django 5.1 on 2025-03-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('demand', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supply', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('affected_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.affectedarea')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.warehouse')),
            ],
        ),
    ]
