# Generated by Django 5.1 on 2025-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('resources_needed', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transportationcost',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='transportationcost',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='AffectedArea',
        ),
        migrations.DeleteModel(
            name='TransportationCost',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
