# Generated by Django 5.1 on 2025-04-03 17:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_allocationresult_affectedarea_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfillment_rate', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PriorityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('units', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='logistics.optimizationresult')),
            ],
        ),
    ]
