# Generated by Django 5.1 on 2025-04-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_optimizationresult_priorityallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectedarea',
            name='priority',
        ),
        migrations.DeleteModel(
            name='PriorityAllocation',
        ),
    ]
